import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, extname, relative, resolve, sep } from "node:path";
import type { BenchConfig, Scenario } from "./types.js";

export type ScaffoldRequest =
  | {
      kind: "element-override";
      selector: string;
      expectedCount: number;
      tag: string;
      outerHTML: string;
      pagePath: string;
      scenario: string;
    }
  | {
      kind: "injected-script";
      name: string;
      pagePath: string;
      scenario: string;
    }
  | {
      kind: "script-override";
      scriptUrl: string;
      source: string;
      pagePath: string;
      scenario: string;
    };

export interface ScaffoldResult {
  scenario: string;
  files: string[];
}

type JsonObject = Record<string, unknown>;

function slug(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
  return normalized || "page-change";
}

function relativeFile(root: string, absolute: string): string {
  return `./${relative(root, absolute).split(sep).join("/")}`;
}

function pathWithin(root: string, ...parts: string[]): string {
  const target = resolve(root, ...parts);
  const prefix = `${resolve(root)}${sep}`;
  if (!target.startsWith(prefix)) throw new Error("Generated path escaped the Mirrorling project.");
  return target;
}

function scenarioToJson(scenario: Scenario, root: string): JsonObject {
  const file = (value: string | undefined): string | undefined =>
    value ? relativeFile(root, value) : undefined;
  return {
    id: scenario.id,
    title: scenario.title,
    description: scenario.description,
    default: scenario.default,
    vars: scenario.vars,
    elementOverrides: scenario.elementOverrides.map((rule) => ({
      ...rule,
      operations: rule.operations.map((operation) => ({ ...operation, file: file(operation.file) })),
    })),
    injectedScripts: scenario.injectedScripts.map((script) => ({ ...script, file: file(script.file) })),
    injectedStyles: scenario.injectedStyles.map((style) => ({ ...style, file: file(style.file) })),
    scriptOverrides: scenario.scriptOverrides.map((rule) => ({ ...rule, file: file(rule.file) })),
    routeOverrides: scenario.routeOverrides.map((rule) => ({ ...rule, file: file(rule.file) })),
    handoffs: scenario.handoffs,
  };
}

function configToJson(config: BenchConfig): JsonObject {
  return {
    server: config.server,
    upstream: config.upstream,
    security: config.security,
    cookies: config.cookies,
    html: config.html,
    development: { ...config.development, enabled: false },
    scenarios: config.scenarios.map((scenario) => scenarioToJson(scenario, config.configDirectory)),
  };
}

async function rawConfig(config: BenchConfig): Promise<JsonObject> {
  try {
    return JSON.parse(await readFile(config.configPath, "utf8")) as JsonObject;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    return configToJson(config);
  }
}

function jsonScenarios(raw: JsonObject): JsonObject[] {
  if (!Array.isArray(raw.scenarios)) raw.scenarios = [];
  return raw.scenarios as JsonObject[];
}

function selectedAuthoringScenario(
  raw: JsonObject,
  config: BenchConfig,
  requestedId: string,
): JsonObject {
  const active = config.scenarios.find((scenario) => scenario.id === requestedId)
    ?? config.scenarios.find((scenario) => scenario.default)
    ?? config.scenarios[0]!;
  const targetId = active.default || ["baseline", "default"].includes(active.id) ? "dev" : active.id;
  const scenarios = jsonScenarios(raw);
  let target = scenarios.find((candidate) => candidate.id === targetId);
  if (!target) {
    target = {
      id: targetId,
      title: targetId === "dev" ? "Development overlays" : active.title,
      description: "Generated by the Mirrorling authoring tools.",
      default: false,
      vars: {},
      elementOverrides: [],
      injectedScripts: [],
      injectedStyles: [],
      scriptOverrides: [],
      routeOverrides: [],
      handoffs: [],
    };
    scenarios.push(target);
  }
  return target;
}

function arrayAt<T extends JsonObject>(object: JsonObject, key: string): T[] {
  if (!Array.isArray(object[key])) object[key] = [];
  return object[key] as T[];
}

function upsertById(items: JsonObject[], value: JsonObject): void {
  const index = items.findIndex((item) => item.id === value.id);
  if (index >= 0) items[index] = value;
  else items.push(value);
}

function matchRule(items: JsonObject[], pagePath: string): JsonObject {
  let rule = items.find((candidate) => candidate.match === pagePath);
  if (!rule) {
    rule = { match: pagePath, operations: [] };
    items.push(rule);
  }
  if (!Array.isArray(rule.operations)) rule.operations = [];
  return rule;
}

async function writeProjectFile(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, { encoding: "utf8", mode: 0o600 });
}

function pagePattern(value: string): string {
  if (!value.startsWith("/") || value.startsWith("//")) return "/";
  return value.split("?")[0] || "/";
}

export async function scaffoldProject(
  config: BenchConfig,
  request: ScaffoldRequest,
): Promise<ScaffoldResult> {
  if (!config.development.enabled || !config.development.allowScaffolding) {
    throw new Error("Scaffolding is disabled. Start Mirrorling with npm run dev.");
  }
  const raw = await rawConfig(config);
  const scenario = selectedAuthoringScenario(raw, config, request.scenario);
  const scenarioId = String(scenario.id);
  const pathMatch = pagePattern(request.pagePath);
  const written: string[] = [];

  if (request.kind === "element-override") {
    if (!request.selector || request.selector.length > 500) throw new Error("A valid selector is required.");
    if (!request.outerHTML || request.outerHTML.length > 512 * 1024) throw new Error("Selected markup is empty or too large.");
    const name = slug(`${request.tag}-${request.selector}`);
    const templatePath = pathWithin(config.configDirectory, "overrides", name, "template.hbs");
    const stylePath = pathWithin(config.configDirectory, "overrides", name, "style.css");
    const template = `{{!--
  Editable replacement for ${request.selector}
  Available context: original, request, scenario, vars, production, staging
  Helpers: text, html, attr, query, productionUrl, stagingUrl, json
--}}
${request.outerHTML}\n`;
    const style = `/* Staging-only styles for ${request.selector}. Production CSS still applies. */\n`;
    await writeProjectFile(templatePath, template);
    await writeProjectFile(stylePath, style);
    const rules = arrayAt<JsonObject>(scenario, "elementOverrides");
    const rule = matchRule(rules, pathMatch);
    const operations = rule.operations as JsonObject[];
    upsertById(operations, {
      id: name,
      type: "replace",
      selector: request.selector,
      file: relativeFile(config.configDirectory, templatePath),
      template: true,
      expect: { count: Math.max(0, Math.floor(request.expectedCount)), tag: request.tag.toLowerCase() },
      onMismatch: "skip",
    });
    upsertById(arrayAt<JsonObject>(scenario, "injectedStyles"), {
      id: `${name}-style`,
      match: pathMatch,
      file: relativeFile(config.configDirectory, stylePath),
    });
    written.push(relativeFile(config.configDirectory, templatePath), relativeFile(config.configDirectory, stylePath));
  } else if (request.kind === "injected-script") {
    const name = slug(request.name);
    const scriptPath = pathWithin(config.configDirectory, "injections", `${name}.js`);
    const source = `/* Independent staging behaviour. This does not replace production JavaScript. */
const mirrorling = window.__MIRRORLING__;
console.info("[mirrorling] ${name} ready", { scenario: mirrorling.scenario, vars: mirrorling.vars });

// Add listeners or test-flow behaviour here. Call mirrorling.handoff("rule-id", { state: {} })
// when this browser flow should continue directly on production.
`;
    await writeProjectFile(scriptPath, source);
    upsertById(arrayAt<JsonObject>(scenario, "injectedScripts"), {
      id: name,
      match: pathMatch,
      file: relativeFile(config.configDirectory, scriptPath),
      timing: "dom-ready",
      module: false,
    });
    written.push(relativeFile(config.configDirectory, scriptPath));
  } else {
    if (request.source.length > 2 * 1024 * 1024) throw new Error("Production script is too large to scaffold (2 MiB limit).");
    const url = new URL(request.scriptUrl, config.server.publicOrigin);
    const allowedOrigins = new Set([new URL(config.server.publicOrigin).origin, new URL(config.upstream.origin).origin]);
    if (!allowedOrigins.has(url.origin)) throw new Error("Only proxied production scripts can be overridden.");
    const base = basename(url.pathname, extname(url.pathname)) || "production-script";
    const name = slug(base);
    const scriptPath = pathWithin(config.configDirectory, "script-overrides", `${name}.js`);
    await writeProjectFile(scriptPath, request.source.endsWith("\n") ? request.source : `${request.source}\n`);
    upsertById(arrayAt<JsonObject>(scenario, "scriptOverrides"), {
      id: name,
      match: url.pathname,
      strategy: "replace",
      file: relativeFile(config.configDirectory, scriptPath),
    });
    written.push(relativeFile(config.configDirectory, scriptPath));
  }

  await mkdir(dirname(config.configPath), { recursive: true });
  await writeFile(config.configPath, `${JSON.stringify(raw, null, 2)}\n`, { encoding: "utf8", mode: 0o600 });
  written.push(relativeFile(config.configDirectory, config.configPath));
  return { scenario: scenarioId, files: written };
}
